name: Python Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script and save output
      run: |
        python main.py > output.txt

    - name: Save output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: python-output
        path: output.txt
